# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-02 13:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repositorio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='almacen',
            options={'verbose_name': 'Almacen', 'verbose_name_plural': 'Almacenes'},
        ),
        migrations.AlterModelOptions(
            name='compra',
            options={'verbose_name': 'Copra', 'verbose_name_plural': 'Compras'},
        ),
        migrations.AlterModelOptions(
            name='proveedor',
            options={'verbose_name': 'Proveedor', 'verbose_name_plural': 'Proveedores'},
        ),
    ]
